blueprint:
  name: Zooz ZEN34 Remote scene control
  description: |
    Use the Zooz ZEN34 remote to trigger Scenes and control devices based on varying scenes. 

    This Blueprint is currently configured for the zwaveJS platform.
    
  domain: automation
  input:
    zwave_device:
      name: Zooz ZEN34
      description: "List of available Zooz ZEN34 switch."
      selector:
          device:
            integration: zwave_js
            manufacturer: Zooz
            model: ZEN34  
    1x_tap_up:
      name: Tap up 1x
      selector:
        action:
      default: []
    1x_tap_down:
      name: Tap down 1x
      selector:
        action:
      default: []
    2x_tap_up:
      name: Tap up 2x
      selector:
        action:
      default: []
    2x_tap_down:
      name: Tap down 2x
      selector:
        action:
      default: []
    3x_tap_up:
      name: Tap up 3x
      selector:
        action:
      default: []
    3x_tap_down:
      name: Tap down 3x
      selector:
        action:
      default: []
    4x_tap_up:
      name: Tap up 4x
      selector:
        action:
      default: []
    4x_tap_down:
      name: Tap down 4x
      selector:
        action:
      default: []
    5x_tap_up:
      name: Tap up 5x
      selector:
        action:
      default: []
    5x_tap_down:
      name: Tap down 5x
      selector:
        action:
      default: []
    hold_up:
      name: Hold up
      selector:
        action:
      default: []
    hold_down:
      name: Hold down
      selector:
        action:
      default: []

mode: single

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data: 
      device_id: !input device_id

variables:
  device_id: !input zwave_device

action:
  - variables:
      button_id: "{{ trigger.event.data.property_key_name }}"
      press_count: "{{ trigger.event.data.value }}"
  - choose:
      - choose:
        # IF 1x tap up
          - conditions:
              - condition: template
                value_template: '{{ button_id == "001" and press_count == "KeyPressed" }}'
            sequence: !input 1x_tap_up
        # IF 1x tap down
          - conditions:
              - condition: template
                value_template: '{{ button_id == "002" and press_count == "KeyPressed" }}'
            sequence: !input 1x_tap_down
        # IF 2x tap up
          - conditions:
              - condition: template
                value_template: '{{ button_id == "001" and press_count == "KeyPressed2x" }}'
            sequence: !input 2x_tap_up
        # IF 2x tap down
          - conditions:
              - condition: template
                value_template: '{{ button_id == "002" and press_count == "KeyPressed2x" }}'
            sequence: !input 2x_tap_down
        # IF 3x tap up
          - conditions:
              - condition: template
                value_template: '{{ button_id == "001" and press_count == "KeyPressed3x" }}'
            sequence: !input 3x_tap_up
        # IF 3x tap down
          - conditions:
              - condition: template
                value_template: '{{ button_id == "002" and press_count == "KeyPressed3x" }}'
            sequence: !input 3x_tap_down
        # IF 4x tap up
          - conditions:
              - condition: template
                value_template: '{{ button_id == "001" and press_count == "KeyPressed4x" }}'
            sequence: !input 4x_tap_up
        # IF 4x tap down
          - conditions:
              - condition: template
                value_template: '{{ button_id == "002" and press_count == "KeyPressed4x" }}'
            sequence: !input 4x_tap_down
        # IF 5x tap up
          - conditions:
              - condition: template
                value_template: '{{ button_id == "001" and press_count == "KeyPressed5x" }}'
            sequence: !input 5x_tap_up
        # IF 5x tap down
          - conditions:
              - condition: template
                value_template: '{{ button_id == "002" and press_count == "KeyPressed5x" }}'
            sequence: !input 5x_tap_down
        # IF hold up
          - conditions:
              - condition: template
                value_template: '{{ button_id == "001" and press_count == "KeyHeldDown" }}'
            sequence: !input hold_up
        # IF hold down
          - conditions:
              - condition: template
                value_template: '{{ button_id == "002" and press_count == "KeyHeldDown" }}'
            sequence: !input hold_down
        # ELSE: unhandled scene_id/scene_data
        default: []
